# DevResidue repo clean script
# Usage: powershell -ExecutionPolicy Bypass -File clean-repo.ps1 [-Full]
#   default: removes build outputs + generated files (keeps dist-portable)
#   -Full  : also removes dist-portable and packaged zips
#
# Reclaimable: target/ (8.7G) + node_modules (122M) + dist + gen + probe bundle
# Never touched: sources, doc/, resources/, Data under dist-portable

param([switch]$Full)

$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent $MyInvocation.MyCommand.Path
$freed = 0

function Remove-Dir([string]$path, [string]$label) {
    if (Test-Path $path -PathType Container) {
        $size = (Get-ChildItem $path -Recurse -File -ErrorAction SilentlyContinue |
            Measure-Object -Property Length -Sum).Sum
        $script:freed += $size
        Remove-Item $path -Recurse -Force
        $mb = "{0:N1}" -f ($size / 1MB)
        Write-Host ("removed {0}  ({1} MB)" -f $label, $mb)
    }
}

function Remove-File([string]$path) {
    if (Test-Path $path -PathType Leaf) {
        $script:freed += (Get-Item $path).Length
        Remove-Item $path -Force
        Write-Host ("removed {0}" -f $path)
    }
}

# Build outputs (regenerable via cargo build / npm ci / npm run build)
Remove-Dir (Join-Path $repo "target")           "target/"
Remove-Dir (Join-Path $repo "src-tauri\target") "src-tauri/target/"
Remove-Dir (Join-Path $repo "node_modules")     "node_modules/"
Remove-Dir (Join-Path $repo "dist")             "dist/"

# tauri-build generated dir (regenerated on every build)
Remove-Dir (Join-Path $repo "src-tauri\gen")    "src-tauri/gen/"

# esbuild probe bundle (regenerated by node src/testing/storeProbes.mjs)
Remove-File (Join-Path $repo "src\testing\store-probes.bundle.mjs")

if ($Full) {
    # Distribution outputs (regenerable via cargo tauri build + release build)
    Remove-Dir (Join-Path $repo "dist-portable") "dist-portable/"
    # Source zips produced by package-src.ps1
    Get-ChildItem $repo -Filter "devresidue-src-*.zip" -File -ErrorAction SilentlyContinue |
        ForEach-Object { Remove-File $_.FullName }
}

$mb = "{0:N1}" -f ($freed / 1MB)
Write-Host ("done. freed ~{0} MB" -f $mb)
