/**
 * Deterministic UI fixtures for browser/store probes.
 *
 * This module is test support only. It never reads or writes the filesystem,
 * starts a process, calls a network, or changes production settings. Paths
 * are deliberately synthetic and remain inside the visible fixture root.
 */

export const FIXTURE_ROOT = "C:/devresidue-fixture";
export const FIXTURE_NOW = 1_735_689_600;

export const UI_SCENARIOS = Object.freeze([
  "risk-matrix",
  "mixed-plan",
  "empty-list",
  "long-path",
  "permission-failure",
  "delayed-completion",
  "partial-results",
  "new-generation",
]);

const DAY = 86_400;
const MiB = 1024 * 1024;

const RISK_DEFINITIONS = Object.freeze({
  safe: {
    slug: "safe-cache",
    display_name: "Fixture safe cache",
    product: "Fixture Tool",
    category: "temporary",
    source: "agent-provider",
    logical_size: 8 * MiB,
    file_count: 12,
    age_days: 2,
    explanation: "Synthetic low-risk cache regenerated by the fixture tool.",
    cleanup_action: { kind: "recycle-bin" },
    evidence: [{ rule_id: null, source: "fixture", detail: "safe fixture" }],
  },
  "regenerable-local": {
    slug: "local-build",
    display_name: "Fixture local build output",
    product: "Fixture Compiler",
    category: "build-artifact",
    source: "kondo",
    logical_size: 64 * MiB,
    file_count: 120,
    age_days: 14,
    explanation: "Synthetic build output that can be recreated locally.",
    cleanup_action: { kind: "recycle-bin" },
    evidence: [{ rule_id: null, source: "fixture", detail: "local rebuild fixture" }],
  },
  "regenerable-download": {
    slug: "download-cache",
    display_name: "Fixture download cache",
    product: "Fixture Package Manager",
    category: "package-cache",
    source: "package-manager",
    logical_size: 128 * MiB,
    file_count: 240,
    age_days: 21,
    explanation: "Synthetic package cache that requires a future download.",
    cleanup_action: {
      kind: "external-command",
      command: {
        executable: "fixture-package-manager",
        args: ["cache", "clean"],
        working_directory: null,
        timeout_secs: 30,
      },
    },
    evidence: [{ rule_id: null, source: "fixture", detail: "redownload fixture" }],
  },
  review: {
    slug: "review-history",
    display_name: "Fixture session history",
    product: "Fixture Agent",
    category: "session",
    source: "agent-provider",
    logical_size: 32 * MiB,
    file_count: 48,
    age_days: 60,
    explanation: "Synthetic history that requires a human review before cleanup.",
    cleanup_action: { kind: "defer", reason: "Fixture review confirmation required" },
    evidence: [{ rule_id: null, source: "fixture", detail: "manual review fixture" }],
  },
  protected: {
    slug: "protected-credentials",
    display_name: "Fixture protected credentials",
    product: "Fixture Auth",
    category: "credential",
    source: "rule",
    logical_size: 4 * MiB,
    file_count: 5,
    age_days: 120,
    explanation: "Synthetic protected data that must never enter a cleanup plan.",
    cleanup_action: { kind: "none" },
    evidence: [{ rule_id: 9001, source: "builtin-protected", detail: "fixture protected" }],
  },
  unknown: {
    slug: "unknown-data",
    display_name: "Fixture unknown developer data",
    product: null,
    category: "unknown",
    source: "rule",
    logical_size: 16 * MiB,
    file_count: 31,
    age_days: 90,
    explanation: "Synthetic unrecognised data that requires a human decision.",
    cleanup_action: { kind: "none" },
    evidence: [{ rule_id: null, source: "fixture", detail: "unknown fixture" }],
  },
});

const RISK_IDS = Object.freeze({
  safe: 101,
  "regenerable-local": 102,
  "regenerable-download": 103,
  review: 104,
  protected: 105,
  unknown: 106,
});

const PLAN_RULES = Object.freeze({
  safe: { action: "recycle", confirmation: "none" },
  "regenerable-local": { action: "recycle", confirmation: "none" },
  "regenerable-download": { action: "execute", confirmation: "redownload" },
  review: { action: "execute", confirmation: "review" },
});

function clone(value) {
  return structuredClone(value);
}

function fixturePath(slug) {
  return `${FIXTURE_ROOT}/${slug}`;
}

/** Creates one fresh ScanItemDto-shaped object. */
export function createFixtureItem(risk, overrides = {}) {
  const definition = RISK_DEFINITIONS[risk];
  if (!definition) throw new RangeError(`Unknown fixture risk: ${risk}`);

  const item = {
    id: RISK_IDS[risk],
    path: fixturePath(definition.slug),
    display_name: definition.display_name,
    product: definition.product,
    category: definition.category,
    risk,
    source: definition.source,
    logical_size: definition.logical_size,
    file_count: definition.file_count,
    last_modified: FIXTURE_NOW - definition.age_days * DAY,
    explanation: definition.explanation,
    cleanup_action: clone(definition.cleanup_action),
    evidence: clone(definition.evidence),
    ...overrides,
  };

  item.cleanup_action = clone(overrides.cleanup_action ?? definition.cleanup_action);
  item.evidence = clone(overrides.evidence ?? definition.evidence);
  return item;
}

/** Creates the complete six-risk matrix in deterministic order. */
export function createRiskMatrix() {
  return Object.keys(RISK_DEFINITIONS).map((risk) => createFixtureItem(risk));
}

/** Creates a ScanSnapshotDto-shaped object with no I/O. */
export function createFixtureSnapshot({
  items = createRiskMatrix(),
  generation = 1,
  scanned_at = FIXTURE_NOW + generation,
  mode = { kind: "fixtures" },
  warnings = [],
  cancelled = false,
} = {}) {
  return {
    scanned_at,
    generation,
    mode: clone(mode),
    items: clone(items),
    warnings: [...warnings],
    cancelled,
  };
}

/** Creates a mixed cleanup plan while keeping protected/unknown skipped. */
export function createMixedPlan({
  items = createRiskMatrix(),
  planId = 301,
  dryRun = false,
} = {}) {
  const itemsByRisk = items.filter((item) => PLAN_RULES[item.risk]);
  const planned = itemsByRisk.map((item) => {
    const rule = PLAN_RULES[item.risk];
    return {
      scanItemId: item.id,
      action: rule.action,
      confirmation: rule.confirmation,
      estimatedSize: item.logical_size,
      path: item.path,
    };
  });
  const skipped = items
    .filter((item) => !PLAN_RULES[item.risk])
    .map((item) => ({
      scanItemId: item.id,
      path: item.path,
      reason: item.risk === "protected" ? "Protected fixture" : "Unknown fixture requires review",
    }));

  return {
    planId,
    dryRun,
    totalEstimatedBytes: planned.reduce((total, item) => total + item.estimatedSize, 0),
    items: planned,
    skipped,
  };
}

/** Creates a CleanupSessionDto-shaped result for plan/dry-run probes. */
export function createFixtureSession({ plan = createMixedPlan(), sessionId = 401, dryRun = false } = {}) {
  const items = plan.items.map((item) => ({
    scanItemId: item.scanItemId,
    path: item.path,
    product: null,
    action: item.action,
    estimatedSize: item.estimatedSize,
    status: dryRun ? "would" : "ok",
    detail: dryRun ? "Fixture dry-run result" : "Fixture execution result",
  }));
  return {
    sessionId,
    planId: plan.planId,
    dryRun,
    totals: {
      plannedBytes: plan.totalEstimatedBytes,
      completedBytes: dryRun ? 0 : plan.totalEstimatedBytes,
      succeeded: dryRun ? 0 : items.length,
      skipped: plan.skipped.length,
      failed: 0,
    },
    items,
    journalDegraded: false,
  };
}

/**
 * Minimal in-memory Backend substitute for store probes. It records calls and
 * can inject one fixed error or a delay; it never touches real I/O.
 */
export function createInertBackend({
  snapshot = createFixtureSnapshot(),
  plan = createMixedPlan(),
  session = createFixtureSession({ plan }),
  delayMs = 0,
  error = null,
} = {}) {
  const calls = [];
  let nextScanId = 501;

  const operation = (method, value) => {
    calls.push({ method });
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (error) {
          reject(clone(error));
          return;
        }
        resolve(clone(value));
      }, delayMs);
    });
  };

  return {
    kind: "mock",
    calls,
    scan: (scope) => {
      calls.push({ method: "scan", scope: clone(scope) });
      return operation("scan-result", { scanId: nextScanId++ });
    },
    cancelScan: (scanId) => operation("cancelScan", Boolean(scanId)),
    getScanResults: () => operation("getScanResults", snapshot),
    createCleanupPlan: () => operation("createCleanupPlan", plan),
    executeCleanupPlan: () => operation("executeCleanupPlan", session),
    clearAllData: () => operation("clearAllData", 0),
  };
}

function longFixturePath() {
  const segments = Array.from({ length: 24 }, (_, index) => `segment-${String(index + 1).padStart(2, "0")}`);
  return `${FIXTURE_ROOT}/${segments.join("/")}/cache`;
}

/** Creates one named UI scenario with fresh data on every call. */
export function createUiScenario(name) {
  switch (name) {
    case "risk-matrix": {
      const items = createRiskMatrix();
      return { name, snapshot: createFixtureSnapshot({ items }), items };
    }
    case "mixed-plan": {
      const items = createRiskMatrix();
      const snapshot = createFixtureSnapshot({ items });
      const plan = createMixedPlan({ items });
      return { name, snapshot, plan, session: createFixtureSession({ plan }) };
    }
    case "empty-list":
      return { name, snapshot: createFixtureSnapshot({ items: [] }) };
    case "long-path": {
      const item = createFixtureItem("unknown", { id: 201, path: longFixturePath() });
      return { name, snapshot: createFixtureSnapshot({ items: [item] }), item };
    }
    case "permission-failure": {
      const error = { code: "engine", message: "Fixture permission denied" };
      const snapshot = createFixtureSnapshot({ items: [createFixtureItem("safe")] });
      return { name, snapshot, error, backend: createInertBackend({ snapshot, error }) };
    }
    case "delayed-completion": {
      const snapshot = createFixtureSnapshot({ items: createRiskMatrix().slice(0, 2) });
      return {
        name,
        delayMs: 40,
        snapshot,
        events: [
          { type: "progress", payload: { scan_id: 501, provider: "fixture", stage: "started" } },
          { type: "item", payload: { scan_id: 501, item: snapshot.items[0] } },
          { type: "done", payload: { scan_id: 501, cancelled: false, total: 2, generation: 1 } },
        ],
        backend: createInertBackend({ snapshot, delayMs: 40 }),
      };
    }
    case "partial-results": {
      const snapshot = createFixtureSnapshot({
        items: createRiskMatrix().slice(0, 2),
        warnings: ["Fixture provider stopped after the first batch"],
        cancelled: true,
      });
      return {
        name,
        snapshot,
        events: [{ type: "done", payload: { scan_id: 501, cancelled: true, total: 2, generation: 1 } }],
      };
    }
    case "new-generation": {
      const before = createFixtureSnapshot({
        generation: 7,
        items: [createFixtureItem("safe", { id: 1, path: `${FIXTURE_ROOT}/old-cache` })],
      });
      const after = createFixtureSnapshot({
        generation: 8,
        items: [createFixtureItem("unknown", { id: 1, path: `${FIXTURE_ROOT}/new-unknown` })],
      });
      return { name, before, after, reusedNumericId: true };
    }
    default:
      throw new RangeError(`Unknown UI fixture scenario: ${name}`);
  }
}

/** Returns fresh instances of every named scenario for table-driven probes. */
export function createScenarioFixtures() {
  return Object.fromEntries(UI_SCENARIOS.map((name) => [name, createUiScenario(name)]));
}
